#20 news
#run ubuntu mallet train
java -jar /media/DataVolume1/github/TopicModeling/bin/LabeledLDA.jar -mode train -train_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_train_text.mallet -train_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_train_label  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_0/models -iteration 50 -top_words 100

#run windows mallet test
java -jar /media/DataVolume1/github/TopicModeling/bin/LabeledLDA.jar -mode test -test_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_text.mallet -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_0/models -prediction_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_0/predictions  -iteration 50 -top_words 100 -use_model_init_test true -show_perplexity_on_test true

#compute label
python ubuntu/py_compute_mallet_predicted_labels.py --infile /media/DataVolume1/py_code_topic_modeling/20_news/fold_0/predictions/test_model_topic_per_document.test_model --outdir /media/DataVolume1/py_code_topic_modeling/20_news/fold_0/loss --prefix predict_labels_fold_0 --true_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label

#compute loss
python ubuntu/py_compute_macro_micro_f1.py




#hierarchical LDA training
java -jar D:/mallet-2.0.7/bin/LabeledHierarchicalLDA.jar -mode train -hier E:/dataset/20news/new_dataset/5_folds/20_news_par_child_hierarchy.txt -train_text E:/dataset/20news/new_dataset/5_folds/20_news_0_fold_train_text.mallet -train_label E:/dataset/20news/new_dataset/5_folds/20_news_0_fold_train_label  -model_out_folder D:/mallet-2.0.7/py_hierarcihcal_lda/20_news/fold_0/models -iteration 20 -top_words 100


#standard LDA
#run windows mallet train
java -jar D:/mallet-2.0.7/bin/StandardLDA.jar -num_topics 20 -mode train -train_text E:/dataset/20news/new_dataset/5_folds/20_news_0_fold_train_text.mallet -model_out_folder D:/mallet-2.0.7/standrad_topic_modeling/20_news/fold_0/models -iteration 50 -top_words 100

#run windows mallet test
java -jar D:/mallet-2.0.7/bin/StandardLDA.jar -mode test -test_text E:/dataset/20news/new_dataset/5_folds/20_news_0_fold_test_text.mallet  -model_out_folder D:/mallet-2.0.7/standrad_topic_modeling/20_news/fold_0/models -prediction_out_folder D:/mallet-2.0.7/standrad_topic_modeling/20_news/fold_0/predictions -iteration 10 -top_words 100 -use_model_init_test true -show_perplexity_on_test true





/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.0 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.1 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.2 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.3 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.4 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.5 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.6 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.7 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_0_fold_test_label   fold_0  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_0
python mail_sender_check_log.py shinelee.thewise@gmail.com "0 mallet job is done " "please check it"
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode train -train_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_train_text.mallet -train_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_train_label  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_1/models -iteration 1000 -top_words 100
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode test -test_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_text.mallet  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_1/models -prediction_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_1/predictions -iteration 100 -top_words 100
python py_compute_mallet_predicted_labels.py --infile /media/DataVolume1/py_code_topic_modeling/20_news/fold_1/predictions/test_model_topic_per_document.test_model --outdir /media/DataVolume1/py_code_topic_modeling/20_news/fold_1/loss --prefix predict_labels_fold_1 --true_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.0 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.1 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.2 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.3 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.4 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.5 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.6 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.7 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_1_fold_test_label   fold_1  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_1
python mail_sender_check_log.py shinelee.thewise@gmail.com "1 mallet job is done " "please check it"
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode train -train_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_train_text.mallet -train_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_train_label  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_2/models -iteration 1000 -top_words 100
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode test -test_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_text.mallet  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_2/models -prediction_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_2/predictions -iteration 100 -top_words 100
python py_compute_mallet_predicted_labels.py --infile /media/DataVolume1/py_code_topic_modeling/20_news/fold_2/predictions/test_model_topic_per_document.test_model --outdir /media/DataVolume1/py_code_topic_modeling/20_news/fold_2/loss --prefix predict_labels_fold_2 --true_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.0 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.1 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.2 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.3 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.4 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.5 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.6 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.7 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_2_fold_test_label   fold_2  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_2
python mail_sender_check_log.py shinelee.thewise@gmail.com "2 mallet job is done " "please check it"
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode train -train_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_train_text.mallet -train_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_train_label  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_3/models -iteration 1000 -top_words 100
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode test -test_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_text.mallet  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_3/models -prediction_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_3/predictions -iteration 100 -top_words 100
python py_compute_mallet_predicted_labels.py --infile /media/DataVolume1/py_code_topic_modeling/20_news/fold_3/predictions/test_model_topic_per_document.test_model --outdir /media/DataVolume1/py_code_topic_modeling/20_news/fold_3/loss --prefix predict_labels_fold_3 --true_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.0 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.1 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.2 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.3 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.4 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.5 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.6 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.7 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_3_fold_test_label   fold_3  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_3
python mail_sender_check_log.py shinelee.thewise@gmail.com "3 mallet job is done " "please check it"
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode train -train_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_train_text.mallet -train_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_train_label  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_4/models -iteration 1000 -top_words 100
/media/DataVolume1/seeuwo/bin/LabeledLDA.jar -mode test -test_text /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_text.mallet  -model_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_4/models -prediction_out_folder /media/DataVolume1/py_code_topic_modeling/20_news/fold_4/predictions -iteration 100 -top_words 100
python py_compute_mallet_predicted_labels.py --infile /media/DataVolume1/py_code_topic_modeling/20_news/fold_4/predictions/test_model_topic_per_document.test_model --outdir /media/DataVolume1/py_code_topic_modeling/20_news/fold_4/loss --prefix predict_labels_fold_4 --true_label /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.0 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.1 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.2 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.3 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.4 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.5 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.6 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
/home/xiao/cplusplus_workspace/HierarchicalFramework/bin/ComputeHierLoss --t 0.7 FILES /media/DataVolume1/datasets/20news/new_dataset/20_news_hierarchy.txt predictions TMP /media/DataVolume1/datasets/20news/new_dataset/5_folds/20_news_4_fold_test_label   fold_4  loss /media/DataVolume1/py_code_topic_modeling/20_news/fold_4
python mail_sender_check_log.py shinelee.thewise@gmail.com "4 mallet job is done " "please check it"
